
#Server Config
server:
  port: 8080
  servlet:
    context-path: /my-ccm

# DB Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    url: jdbc:h2:file:${user.home}/h2/my-ccm
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

xml:
  file:
    path: .\src\main\resources\xmlFiles
    
xsl:
  file:
    path: .\src\main\resources\xsl\myccm.xsl
    
fop:
  conf:
    file:
      path: .\src\main\resources\fopConfig\fop.xconf
      
output:
  file:
    path: ${user.home}/Desktop/my-ccm/PDF
    